# Generated by Django 5.1.5 on 2025-01-27 18:16

import Students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=Students.models.student_directory_path),
        ),
    ]
