# Generated by Django 5.1.5 on 2025-01-28 14:56

import Teachers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0002_alter_teacher_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=Teachers.models.teacher_directory_path),
        ),
    ]
